baseurl = "/"
languageCode = "en-us"
theme = "terminal"
paginate = 5

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "pink"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 3
  # show selector to switch language
  showLanguageSelector = false
  # set theme to full screen width
  fullWidthTheme = false
  # center theme with default width
  centerTheme = true
  # set a custom favicon (default is a `themeColor` square)
  favicon = "favicon.ico"

  siteURL = "https://blog.noahkernis.com"

[languages]
  [languages.en]
    languageName = "English"
    title = "Noah Kernis - The Blog"
    subtitle = "Blog is a weird word"
    keywords = "blog itp technology art learning noah kernis"
    copyright = "All The Rights - All Of Time - All To Noah Kernis"
    menuMore = "Show more"
    readMore = "Read post"
    readOtherPosts = "Read other posts"
    taglines = [
      "Only at participating locations", 
      "No dice - roll again", 
      "I still can't beleive it's not butter",
      "All employees must use the service entrance",
      "Oh - I'm sorry - you just missed them",
      "Freshness guaranteed",
      "Terms of service - use it or don't",
      "[ Insert joke here ]",
      "The input goes nowhere ==> <input type='text'>",
      "Clicking the button does nothing ==> <button class='nothing-button'>the button</button>",
      "Pick a number - any number - for no reason ==> <input type='number'>",
      "Turn the \"radio\" on ==> <input type='radio'>",
      "I am a computer - beep bop boop",
      "Commenting is prohibited - for everyone's sake",
      "I'll get to it at some point"
    ]

    [languages.en.params.logo]
      logoText = "Noah Kernis - The Blog"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"

      [[languages.en.menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags"

      [[languages.en.menu.main]]
        identifier = "contact"
        name = "Contact"
        url = "/contact"

[privacy]
  [privacy.disqus]
    disable = false

  [privacy.googleAnalytics]
    disable = false
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = true

  [privacy.instagram]
    disable = false
    simple = true
    disableInlineCSS = true

  [privacy.twitter]
    disable = false
    enableDNT = true
    simple = true
    disableInlineCSS = true

  [privacy.vimeo]
    disable = false
    simple = true

  [privacy.youtube]
    disable = false
    privacyEnhanced = true